import { useRouter } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useEffect } from 'react';
import { Button, Card, Screen, colors, s } from '@/ui';
import { useStore } from '@/store';
import { VOCAB } from '@/vocab';
import { buildItem } from '@/items';
import { useMemo } from 'react';
export default function Quiz(){ const r=useRouter(); const st=useStore(); useEffect(()=>{ if(!st.todayIds.length) st.startSession(); },[]); const ids=st.todayIds.length?st.todayIds:VOCAB.slice(0,10).map(w=>w.id); const done=st.todayIds.length>0 && st.sessionIndex>=ids.length; const idx=Math.min(st.sessionIndex, ids.length-1); const w=st.getWord(ids[idx]); const item=useMemo(()=>buildItem(w,VOCAB,st.stats[w.id]?.seen??0),[w.id,st.stats[w.id]?.seen]); const choose=(choice:string)=>{const correct=choice===item.answer; st.recordQuiz(w.id,correct); r.push({pathname:'/results',params:{word:w.word,correct:correct?'1':'0',explanation:item.explanation}});}; if(done) return <Screen><View style={{flex:1,justifyContent:'center'}}><View style={{alignItems:'center'}}><Text style={{fontSize:52}}>🎯</Text><Text style={[s.title,{marginTop:12,textAlign:'center'}]}>Session complete</Text><Text style={[s.subtitle,{marginTop:8,textAlign:'center'}]}>You answered all {ids.length} words. Start a new set to keep practising.</Text></View><View style={{marginTop:20,gap:10}}><Button label="START A NEW SET" onPress={()=>{st.startSession(); r.replace('/learn');}}/><Button label="VIEW PROGRESS" secondary onPress={()=>r.replace('/progress')}/></View></View></Screen>;
  return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}><View style={s.row}><Text style={{fontSize:14,fontWeight:'700',color:colors.muted}}>{item.label}</Text><Text style={{fontSize:14,fontWeight:'800'}}>{idx+1}/{ids.length}</Text></View><Text style={[s.title,{marginTop:18}]}>Choose the best fit.</Text><Card style={{marginTop:18}}><Text style={{fontSize:20,lineHeight:30,fontWeight:'600'}}>{item.prompt}</Text></Card><View style={{gap:10,marginTop:16}}>{item.choices.map(c=><Pressable key={c} onPress={()=>choose(c)} style={({pressed})=>[{padding:17,borderRadius:16,borderWidth:1,borderColor:colors.line,backgroundColor:'#fff'},pressed&&{opacity:.72}]}><Text style={{fontSize:17,fontWeight:'700'}}>{c}</Text></Pressable>)}</View><Text style={[s.subtitle,{marginTop:14}]}>This prototype uses original practice questions modeled on vocabulary-in-context practice; it does not copy official SAT questions.</Text></ScrollView></Screen> }
