// Build data/wordnet.json: a compact, offline subset of Princeton WordNet for words the
// SAT dictionary lacks. Usage: node scripts/build-wordnet.mjs <path-to-wordnet-db/dict>
//
// Row format (tuple, to keep the bundle small):
//   lemma: [pos, definition, example, "syn1,syn2,syn3", altDefinition]
// Common words (WordNet counts them in tagged text) keep two meanings; rarer words keep one
// short meaning. Taxonomy, place and other encyclopedia-style entries are dropped for rare words.
// Output is sharded by first letter (data/wordnet/a.json ...) so only the shards a scan touches load.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';

const dir = process.argv[2];
if (!dir) { console.error('usage: node scripts/build-wordnet.mjs <dict-dir>'); process.exit(1); }
const POS = { noun: 'noun', verb: 'verb', adj: 'adjective', adv: 'adverb' };

const dataCache = {};
const dataLines = pos => dataCache[pos] ??= readFileSync(join(dir, `data.${pos}`), 'latin1');
const offsets = {};   // pos -> Map(offset -> line)
function synset(pos, off) {
  if (!offsets[pos]) {
    const m = new Map();
    for (const line of dataLines(pos).split('\n')) { if (line.startsWith(' ')) continue; const o = line.slice(0, 8); if (/^\d{8}$/.test(o)) m.set(o, line); }
    offsets[pos] = m;
  }
  const line = offsets[pos].get(off);
  if (!line) return null;
  const [head, gloss = ''] = line.split(' | ');
  const f = head.split(' ');
  const wcnt = parseInt(f[3], 16);
  const words = [];
  for (let i = 0; i < wcnt; i++) words.push(f[4 + i * 2].replace(/\(.*\)$/, '').replace(/_/g, ' '));
  const parts = gloss.split(/;\s+(?=")/);
  const def = parts[0].replace(/;\s*"[^]*$/, '').trim();
  const examples = [...gloss.matchAll(/"([^"]+)"/g)].map(m => m[1].trim());
  return { words, def, examples };
}

const best = new Map();   // lemma -> { score, senses: [{pos, def, ex, syns}] }
for (const [file, pos] of Object.entries(POS)) {
  for (const line of readFileSync(join(dir, `index.${file}`), 'latin1').split('\n')) {
    if (!line || line.startsWith(' ')) continue;
    const f = line.trim().split(/\s+/);
    const lemma = f[0];
    if (!/^[a-z][a-z-]{2,}$/.test(lemma)) continue;           // single words, 3+ letters
    const ptrCnt = parseInt(f[3], 10);
    const senseCnt = parseInt(f[4 + ptrCnt], 10);
    const tagCnt = parseInt(f[5 + ptrCnt], 10);
    const rare = tagCnt < 1;
    const offs = f.slice(6 + ptrCnt, 6 + ptrCnt + senseCnt);
    const senses = [];
    for (const off of offs.slice(0, rare ? 1 : 2)) {
      const s = synset(file, off);
      if (!s || !s.def) continue;
      if (rare && /\b(genus|family|species|order|class|phylum|subfamily|suborder|town|city|village|river|island|county|province|republic|capital|district|born|died|a unit of|variety of)\b/i.test(s.def)) continue;
      senses.push({
        pos, def: s.def.length > (rare ? 110 : 140) ? s.def.slice(0, rare ? 107 : 137).replace(/\s+\S*$/, '') + '…' : s.def,
        ex: s.examples.find(e => e.length <= (rare ? 90 : 120) && e.toLowerCase().includes(lemma.slice(0, Math.max(3, lemma.length - 3)))) ?? '',
        syns: s.words.filter(w => w.toLowerCase() !== lemma && !w.includes(' ') && /^[a-z-]+$/.test(w)).slice(0, rare ? 2 : 3),
      });
    }
    if (!senses.length) continue;
    const prev = best.get(lemma);
    if (!prev) best.set(lemma, { score: tagCnt, senses });
    else { prev.senses.push(...senses); prev.score += tagCnt; if (tagCnt > prev.top) prev.top = tagCnt; }
    const cur = best.get(lemma); cur.top = Math.max(cur.top ?? 0, tagCnt);
    // keep the most frequent part of speech first
    if (cur.senses.length > 1 && tagCnt === cur.top) cur.senses = [...senses, ...cur.senses.filter(s => !senses.includes(s))];
  }
}

const out = {};
for (const [lemma, v] of [...best.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  const [a, b] = v.senses;
  out[lemma] = [a.pos, a.def, a.ex, a.syns.join(','), b ? `${b.pos === a.pos ? '' : `(${b.pos}) `}${b.def}` : ''];
}
rmSync('data/wordnet', { recursive: true, force: true });
mkdirSync('data/wordnet', { recursive: true });
const shards = {};
for (const [k, v] of Object.entries(out)) (shards[k[0]] ??= {})[k] = v;
let bytes = 0;
for (const [c, obj] of Object.entries(shards)) { const s = JSON.stringify(obj); bytes += s.length; writeFileSync(`data/wordnet/${c}.json`, s); }
copyFileSync(join(dir, '..', 'LICENSE'), 'data/WORDNET-LICENSE.txt');
// static require table: Metro needs literal paths; each shard is only evaluated when asked for
const letters = Object.keys(shards).sort();
writeFileSync('src/wordnetShards.ts', `// GENERATED by scripts/build-wordnet.mjs. Do not edit.\n/* eslint-disable */\nexport const loadShard = (c: string): Record<string, string[]> | null => {\n  switch (c) {\n${letters.map(c => `    case '${c}': return require('../data/wordnet/${c}.json');`).join('\n')}\n    default: return null;\n  }\n};\n`);
const n = Object.keys(out).length;
const withEx = Object.values(out).filter(r => r[2]).length;
console.log(`wrote data/wordnet/*.json: ${n} words, ${withEx} with examples, ${(bytes / 1024 / 1024).toFixed(1)} MB in ${letters.length} shards`);
