export type Difficulty = 'Easy' | 'Medium' | 'Hard';
export type Word = {
  id: string;
  word: string;
  pronunciation: string;
  partOfSpeech: string;
  definition: string;
  example: string;
  synonyms: string[];
  antonyms: string[];
  difficulty: Difficulty;
  priority: number;
  category: string;
  question: string;
  choices: string[];
  answer: string;
  explanation: string;
};

const W = (id: string, word: string, pronunciation: string, partOfSpeech: string, definition: string, example: string, synonyms: string[], antonyms: string[], difficulty: Difficulty, priority: number, category: string, question: string, choices: string[], answer: string, explanation: string): Word => ({ id, word, pronunciation, partOfSpeech, definition, example, synonyms, antonyms, difficulty, priority, category, question, choices, answer, explanation });

export const VOCAB: Word[] = [
W('abate','abate','/əˈbeɪt/','verb','to become less intense or severe','By evening, the storm began to abate.',['diminish','lessen','subside'],['intensify'], 'Medium',88,'Words in Context','After several hours, the winds began to _____, allowing crews to work safely.',['abate','accelerate','consolidate','provoke'],'abate','The sentence describes the winds becoming less intense, so abate is precise.'),
W('ambiguous','ambiguous','/æmˈbɪɡjuəs/','adjective','open to more than one interpretation','The ambiguous wording of the rule caused confusion.',['unclear','equivocal','vague'],['explicit'], 'Medium',93,'Words in Context','Because the instructions were _____, students were unsure what the teacher expected.',['ambiguous','meticulous','conspicuous','conventional'],'ambiguous','Ambiguous means unclear because it allows multiple interpretations.'),
W('arbitrary','arbitrary','/ˈɑːrbətreri/','adjective','based on personal choice rather than a clear rule','The committee rejected the arbitrary limit.',['capricious','random','unreasoned'],['reasoned'], 'Hard',91,'Reasoning','The committee wanted a consistent policy, not an _____ rule that changed from case to case.',['arbitrary','empirical','coherent','integral'],'arbitrary','An arbitrary rule lacks a consistent rational basis.'),
W('corroborate','corroborate','/kəˈrɑːbəˌreɪt/','verb','to confirm or support with evidence','The second study helped corroborate the original finding.',['confirm','substantiate','verify'],['contradict'], 'Hard',94,'Evidence','The witness statement was useful, but investigators needed records to _____ it.',['corroborate','mitigate','deter','reconcile'],'corroborate','Corroborate means to confirm or strengthen a claim with evidence.'),
W('diminish','diminish','/dɪˈmɪnɪʃ/','verb','to make or become less','The medication diminished the pain.',['decrease','lessen','reduce'],['increase'], 'Easy',90,'Cause & Effect','The thick curtains helped _____ the amount of sunlight entering the room.',['diminish','exacerbate','elicit','facilitate'],'diminish','The curtains reduced the amount of sunlight.'),
W('elicit','elicit','/ɪˈlɪsɪt/','verb','to draw out a response, reaction, or information','The question elicited a thoughtful response.',['draw out','evoke','provoke'],['suppress'], 'Hard',89,'Words in Context','The interviewer asked an open-ended question to _____ detailed responses from participants.',['elicit','inhibit','contradict','deter'],'elicit','Elicit means to draw something out, such as a response or information.'),
W('empirical','empirical','/ɛmˈpɪrɪkəl/','adjective','based on observation or experiment','The researchers sought empirical evidence for the claim.',['observational','evidence-based','experimental'],['theoretical'], 'Hard',90,'Evidence','The researchers supported their conclusion with _____ data collected from repeated trials.',['empirical','arbitrary','ambiguous','sporadic'],'empirical','Empirical evidence comes from observation or experiment.'),
W('equivocal','equivocal','/ɪˈkwɪvəkəl/','adjective','open to multiple interpretations; uncertain or ambiguous','Her equivocal answer revealed no clear position.',['ambiguous','uncertain','noncommittal'],['unequivocal'], 'Hard',87,'Words in Context','The mayor gave an _____ response, avoiding a clear yes or no.',['equivocal','explicit','meticulous','fundamental'],'equivocal','An equivocal response is deliberately unclear or open to interpretation.'),
W('exacerbate','exacerbate','/ɪɡˈzæsərbeɪt/','verb','to make a problem or situation worse','The delay exacerbated the shortage.',['worsen','aggravate','intensify'],['alleviate'], 'Hard',95,'Cause & Effect','Adding more restrictions could _____ the shortage rather than solve it.',['exacerbate','mitigate','corroborate','reconcile'],'exacerbate','To exacerbate a problem is to make it worse.'),
W('facilitate','facilitate','/fəˈsɪləteɪt/','verb','to make something easier or more likely to happen','The new software facilitates communication among teams.',['enable','assist','ease'],['hinder'], 'Medium',90,'Cause & Effect','The online form was designed to _____ the application process.',['facilitate','impede','undermine','contradict'],'facilitate','Facilitate means to make a process easier.'),
W('inhibit','inhibit','/ɪnˈhɪbɪt/','verb','to prevent or slow an action or process','Fear can inhibit creativity.',['restrain','hinder','suppress'],['encourage'], 'Hard',88,'Cause & Effect','Excessive noise can _____ a student\'s ability to concentrate.',['inhibit','elicit','facilitate','substantiate'],'inhibit','Inhibit means to prevent or restrain a process or behavior.'),
W('inherent','inherent','/ɪnˈhɪrənt/','adjective','naturally existing as a basic part of something','Risk is inherent in the activity.',['intrinsic','built-in','essential'],['extraneous'], 'Hard',92,'Meaning & Relationships','The researchers recognized that some uncertainty was _____ in the measurement process.',['inherent','arbitrary','sporadic','subsequent'],'inherent','Inherent means naturally present as part of something.'),
W('mitigate','mitigate','/ˈmɪtəˌɡeɪt/','verb','to make something less severe, harmful, or serious','The policy was designed to mitigate the effects of pollution.',['alleviate','reduce','lessen'],['exacerbate'], 'Hard',95,'Cause & Effect','The city planted trees to _____ the effects of extreme summer heat.',['mitigate','exacerbate','elicit','contradict'],'mitigate','Mitigate means to make a harmful or severe effect less serious.'),
W('novel','novel','/ˈnɑːvəl/','adjective','new, original, or unusual','The team proposed a novel approach to the problem.',['innovative','original','unprecedented'],['conventional'], 'Medium',86,'Words in Context','The researchers developed a _____ technique that differed from established methods.',['novel','conventional','arbitrary','sporadic'],'novel','Here novel means new or original.'),
W('pragmatic','pragmatic','/præɡˈmætɪk/','adjective','focused on practical results rather than theory','The committee took a pragmatic approach to the budget.',['practical','realistic','sensible'],['idealistic'], 'Hard',85,'Reasoning','Rather than debate every theoretical possibility, the manager took a _____ approach focused on what would work.',['pragmatic','arbitrary','equivocal','conspicuous'],'pragmatic','Pragmatic describes a practical, results-focused approach.'),
W('profound','profound','/prəˈfaʊnd/','adjective','very great in depth, intensity, or significance','The discovery had a profound effect on the field.',['deep','significant','far-reaching'],['superficial'], 'Medium',83,'Words in Context','The discovery had a _____ effect on how scientists understood the disease.',['profound','sporadic','discrete','tentative'],'profound','The effect was described as very significant and far-reaching.'),
W('reconcile','reconcile','/ˈrɛkənˌsaɪl/','verb','to make two ideas, accounts, or people compatible','The analyst reconciled the two sets of data.',['resolve','harmonize','square'],['conflict'], 'Hard',92,'Reasoning','Researchers had to _____ two results that initially seemed inconsistent.',['reconcile','elicit','diminish','facilitate'],'reconcile','To reconcile is to make apparently conflicting information fit together.'),
W('subsequent','subsequent','/ˈsʌbsɪkwənt/','adjective','coming after something else','Subsequent tests confirmed the result.',['following','later','ensuing'],['preceding'], 'Medium',84,'Sequence','The initial study was promising, but _____ experiments produced different results.',['subsequent','inherent','arbitrary','conspicuous'],'subsequent','Subsequent means occurring later or after something else.'),
W('substantiate','substantiate','/səbˈstænʃieɪt/','verb','to support a claim with evidence','The data substantiated her conclusion.',['support','verify','corroborate'],['refute'], 'Hard',94,'Evidence','The scientist needed additional trials to _____ the surprising claim.',['substantiate','mitigate','deter','abate'],'substantiate','Substantiate means to support a claim with evidence.'),
W('transcend','transcend','/trænˈsɛnd/','verb','to go beyond or rise above a limit','The work transcends traditional categories.',['surpass','exceed','rise above'],['confine'], 'Hard',82,'Relationships','The artist\'s work seemed to _____ the boundaries between science and art.',['transcend','inhibit','diminish','contradict'],'transcend','To transcend a boundary is to go beyond it.'),
W('viable','viable','/ˈvaɪəbəl/','adjective','capable of working successfully or being sustained','The team developed a viable solution.',['feasible','workable','practical'],['impractical'], 'Medium',92,'Reasoning','The proposal would be a _____ option only if its costs could be reduced.',['viable','ambiguous','sporadic','conspicuous'],'viable','Viable means capable of working successfully.'),
W('advocate','advocate','/ˈædvəˌkeɪt/','verb','to publicly support a cause or idea','Many scientists advocate stricter pollution controls.',['support','champion','promote'],['oppose'], 'Medium',88,'Argument','The researchers _____ using local data instead of a national average.',['advocate','contradict','inhibit','deter'],'advocate','As a verb, advocate means to publicly support an idea or course of action.'),
W('conventional','conventional','/kənˈvɛnʃənəl/','adjective','based on what is traditional or commonly accepted','The study used a conventional testing method.',['traditional','standard','customary'],['novel'], 'Easy',80,'Comparison','The team chose a _____ method because it had been widely tested.',['conventional','novel','arbitrary','equivocal'],'conventional','Conventional means traditional or commonly accepted.'),
W('conspicuous','conspicuous','/kənˈspɪkjuəs/','adjective','easy to see or notice','The bright sign was conspicuous from a distance.',['noticeable','prominent','obvious'],['inconspicuous'], 'Medium',79,'Words in Context','The bright orange marker was especially _____ against the white background.',['conspicuous','discrete','inherent','tentative'],'conspicuous','The marker was easy to notice because of its contrast.'),
W('discrete','discrete','/dɪˈskriːt/','adjective','separate or distinct','The study examined three discrete populations.',['separate','distinct','individual'],['continuous'], 'Hard',78,'Relationships','The survey divided participants into three _____ groups for analysis.',['discrete','profound','subsequent','arbitrary'],'discrete','Discrete means separate and distinct rather than continuous.'),
W('integral','integral','/ˈɪntəɡrəl/','adjective','necessary to make a whole complete','Trust is integral to effective teamwork.',['essential','fundamental','vital'],['optional'], 'Medium',89,'Relationships','Reliable data are _____ to the study\'s conclusions; without them, the analysis would fail.',['integral','sporadic','tentative','ambiguous'],'integral','Integral means necessary to the completeness or function of something.'),
W('inconsistent','inconsistent','/ˌɪnkənˈsɪstənt/','adjective','not in agreement or not following a steady pattern','The two accounts were inconsistent.',['contradictory','variable','conflicting'],['consistent'], 'Medium',90,'Reasoning','The results were _____ with the theory, so researchers investigated further.',['inconsistent','integral','novel','explicit'],'inconsistent','Inconsistent means not matching or not agreeing.'),
W('meticulous','meticulous','/məˈtɪkjələs/','adjective','very careful and precise','She kept meticulous records of every trial.',['careful','thorough','precise'],['careless'], 'Hard',85,'Academic Practice','The lab assistant was _____ about labeling every sample correctly.',['meticulous','arbitrary','sporadic','equivocal'],'meticulous','Meticulous means extremely careful and precise.'),
W('predominant','predominant','/prɪˈdɑːmənənt/','adjective','most common, important, or influential','Rain was the predominant feature of the climate.',['prevailing','main','dominant'],['minor'], 'Medium',84,'Comparison','The _____ view among researchers was that more data were needed.',['predominant','tentative','discrete','ambiguous'],'predominant','The predominant view was the most widely held or influential.'),
W('reluctant','reluctant','/rɪˈlʌktənt/','adjective','unwilling or hesitant to do something','The witness was reluctant to speculate.',['hesitant','unwilling','reserved'],['eager'], 'Easy',76,'Attitude','The scientist was _____ to publish the result before repeating the experiment.',['reluctant','conspicuous','profound','fundamental'],'reluctant','Reluctant means hesitant or unwilling.'),
W('scrutinize','scrutinize','/ˈskruːtəˌnaɪz/','verb','to examine very carefully','Reviewers scrutinized the evidence for errors.',['examine','inspect','analyze'],['overlook'], 'Hard',91,'Evidence','Before accepting the claim, the panel decided to _____ the underlying data.',['scrutinize','diminish','advocate','transcend'],'scrutinize','Scrutinize means to examine closely and carefully.'),
W('sporadic','sporadic','/spəˈrædɪk/','adjective','occurring irregularly rather than continuously','The region experienced sporadic power outages.',['irregular','intermittent','occasional'],['constant'], 'Medium',78,'Patterns','The signal was _____, appearing for a few seconds and then disappearing.',['sporadic','integral','conventional','explicit'],'sporadic','Sporadic events occur irregularly rather than steadily.'),
W('tentative','tentative','/ˈtɛntətɪv/','adjective','not certain or final; subject to change','The researchers offered a tentative explanation.',['provisional','uncertain','preliminary'],['definite'], 'Medium',87,'Reasoning','Because the evidence was limited, the researchers described their conclusion as _____.',['tentative','conspicuous','integral','predominant'],'tentative','A tentative conclusion is not final and may change with new evidence.'),
W('undermine','undermine','/ˌʌndərˈmaɪn/','verb','to weaken or damage gradually','The error undermined confidence in the report.',['weaken','erode','impair'],['strengthen'], 'Hard',93,'Cause & Effect','Repeated inconsistencies began to _____ confidence in the study’s conclusions.',['undermine','corroborate','facilitate','elicit'],'undermine','Undermine means to weaken something, often gradually or indirectly.'),
W('unprecedented','unprecedented','/ʌnˈprɛsɪˌdɛntɪd/','adjective','never having happened before','The city faced an unprecedented heat wave.',['unparalleled','new','historic'],['ordinary'], 'Medium',83,'Comparison','The scale of the event was _____, with no similar case in the region\'s history.',['unprecedented','conventional','sporadic','subsequent'],'unprecedented','Unprecedented means never before seen or experienced.'),
W('coherent','coherent','/koʊˈhɪrənt/','adjective','logical, connected, and easy to understand','The report presented a coherent explanation.',['logical','consistent','clear'],['confusing'], 'Medium',89,'Organization','The evidence formed a _____ argument in favor of the proposed explanation.',['coherent','arbitrary','sporadic','ambiguous'],'coherent','A coherent argument is logically connected and understandable.'),
W('compelling','compelling','/kəmˈpɛlɪŋ/','adjective','convincing or strongly persuasive','The researchers presented compelling evidence.',['convincing','persuasive','forceful'],['unconvincing'], 'Medium',90,'Argument','The new evidence was so _____ that the committee changed its recommendation.',['compelling','tentative','discrete','conventional'],'compelling','Compelling evidence is persuasive enough to strongly influence judgment.'),
W('concise','concise','/kənˈsaɪs/','adjective','brief but complete and clear','Her concise summary captured the main findings.',['brief','succinct','terse'],['verbose'], 'Easy',82,'Communication','The editor asked for a more _____ explanation that kept the key points.',['concise','ambiguous','profound','sporadic'],'concise','Concise means brief without unnecessary detail.'),
W('contradict','contradict','/ˌkɑːntrəˈdɪkt/','verb','to state the opposite of or be incompatible with','The later findings contradicted the earlier claim.',['oppose','deny','conflict with'],['confirm'], 'Medium',91,'Reasoning','The new measurements appear to _____ the original prediction.',['contradict','corroborate','facilitate','mitigate'],'contradict','The new measurements conflict with the original prediction.'),
W('cumulative','cumulative','/ˈkjuːmjələtɪv/','adjective','increasing by successive additions','The cumulative effects of small errors can be substantial.',['combined','aggregate','accumulated'],['isolated'], 'Hard',86,'Cause & Effect','Each delay was minor, but their _____ effect was significant.',['cumulative','sporadic','arbitrary','discrete'],'cumulative','Cumulative describes an effect that grows through repeated additions.'),
W('deteriorate','deteriorate','/dɪˈtɪriəˌreɪt/','verb','to become worse in condition or quality','Without maintenance, the structure will deteriorate.',['decline','worsen','degrade'],['improve'], 'Medium',87,'Change','Without repairs, the building\'s condition will continue to _____.',['deteriorate','transcend','corroborate','elicit'],'deteriorate','Deteriorate means to become worse.'),
W('explicit','explicit','/ɪkˈsplɪsɪt/','adjective','stated clearly and directly','The instructions were explicit.',['clear','direct','unambiguous'],['implicit'], 'Easy',84,'Words in Context','The policy is _____ about which students qualify for the program.',['explicit','equivocal','tentative','sporadic'],'explicit','Explicit information is stated directly and clearly.'),
W('feasible','feasible','/ˈfiːzəbəl/','adjective','possible and practical to accomplish','The engineers proposed a feasible design.',['practical','possible','workable'],['impossible'], 'Medium',88,'Reasoning','The team rejected the plan because it was not technically _____.',['feasible','conspicuous','profound','subsequent'],'feasible','Feasible means possible to accomplish in practice.'),
W('fundamental','fundamental','/ˌfʌndəˈmɛntl/','adjective','basic and essential to a system or idea','Trust is fundamental to the partnership.',['basic','essential','foundational'],['secondary'], 'Easy',86,'Relationships','Understanding the original assumption is _____ to interpreting the rest of the argument.',['fundamental','sporadic','tentative','arbitrary'],'fundamental','Fundamental means basic and essential.'),
W('hypothesis','hypothesis','/haɪˈpɑːθəsɪs/','noun','a testable explanation or proposed idea','The researchers tested the hypothesis with new data.',['theory','proposal','supposition'],['certainty'], 'Medium',90,'Evidence','The experiment was designed to test the researchers\' _____.',['hypothesis','antonym','dilemma','anecdote'],'hypothesis','A hypothesis is a proposed explanation that can be tested.'),
W('impede','impede','/ɪmˈpiːd/','verb','to slow down or obstruct','Heavy traffic impeded the emergency response.',['hinder','obstruct','hamper'],['facilitate'], 'Hard',89,'Cause & Effect','Construction along the road could _____ deliveries to the neighborhood.',['impede','facilitate','corroborate','elicit'],'impede','Impede means to make progress more difficult or slower.'),
W('innovative','innovative','/ˈɪnəˌveɪtɪv/','adjective','introducing new ideas or methods','The company developed an innovative solution.',['creative','novel','original'],['conventional'], 'Medium',88,'Words in Context','The team proposed an _____ design that reduced both cost and waste.',['innovative','conventional','ambiguous','tentative'],'innovative','Innovative means introducing a new or original approach.'),
W('nuance','nuance','/ˈnuːɑːns/','noun','a subtle distinction or variation in meaning','The essay captured the nuance of the debate.',['subtlety','distinction','refinement'],['oversimplification'], 'Hard',84,'Meaning & Relationships','A careful reader notices the _____ between the author’s two similar claims.',['nuance','contradiction','hypothesis','precedent'],'nuance','A nuance is a subtle distinction that can change interpretation.'),
W('precise','precise','/prɪˈsaɪs/','adjective','exact and accurate','The study provides precise measurements.',['exact','accurate','specific'],['vague'], 'Easy',85,'Words in Context','The instructions must be _____ enough that every participant follows the same procedure.',['precise','sporadic','ambiguous','tentative'],'precise','Precise means exact and accurate.'),
W('refute','refute','/rɪˈfjuːt/','verb','to prove a claim or argument false','The experiment refuted the proposed explanation.',['disprove','rebut','invalidate'],['support'], 'Hard',93,'Evidence','The researchers found evidence that could _____ the original claim.',['refute','corroborate','mitigate','facilitate'],'refute','Refute means to show that a claim is false or unsupported.'),
W('rigorous','rigorous','/ˈrɪɡərəs/','adjective','thorough, exacting, and strict','The study used rigorous standards for inclusion.',['thorough','strict','careful'],['sloppy'], 'Hard',89,'Academic Practice','The journal required a _____ review process before publication.',['rigorous','arbitrary','sporadic','equivocal'],'rigorous','A rigorous process applies careful, demanding standards.'),
W('salient','salient','/ˈseɪliənt/','adjective','most noticeable or important','The report highlighted the salient features of the proposal.',['prominent','important','notable'],['minor'], 'Hard',83,'Words in Context','The analyst focused on the most _____ factor affecting the decision.',['salient','sporadic','inherent','subsequent'],'salient','Salient means especially important or noticeable.'),
W('scrupulous','scrupulous','/ˈskruːpjələs/','adjective','very careful to do what is correct or ethical','The researcher was scrupulous about reporting limitations.',['conscientious','careful','principled'],['careless'], 'Hard',80,'Academic Practice','The editor was _____ about checking every citation before publication.',['scrupulous','arbitrary','novel','sporadic'],'scrupulous','Scrupulous describes extreme care and attention to correctness.'),
W('subtle','subtle','/ˈsʌtl/','adjective','not obvious; difficult to detect or understand','The author makes a subtle distinction between the two ideas.',['nuanced','delicate','faint'],['obvious'], 'Medium',81,'Meaning & Relationships','The difference between the two arguments is subtle rather than _____.',['obvious','implicit','integral','tentative'],'obvious','The sentence contrasts a subtle difference with an obvious one.'),
W('versatile','versatile','/ˈvɜːrsətəl/','adjective','able to adapt to many different uses or situations','The tool is versatile enough for several applications.',['adaptable','flexible','multifunctional'],['limited'], 'Medium',77,'Words in Context','Because it can be used in several settings, the device is especially _____.',['versatile','arbitrary','conspicuous','sporadic'],'versatile','Versatile means useful across many different situations or purposes.'),
W('skeptical','skeptical','/ˈskɛptɪkəl/','adjective','not easily convinced; inclined to doubt a claim','The reviewers remained skeptical of the result until a second laboratory repeated the experiment.',['doubtful','dubious','unconvinced'],['credulous'], 'Hard',92,'Tone & Attitude','Although the early findings looked promising, the committee stayed _____ until independent researchers confirmed them.',['skeptical','enthusiastic','indifferent','remorseful'],'skeptical','Skeptical describes withholding belief until stronger proof arrives.'),
W('ambivalent','ambivalent','/æmˈbɪvələnt/','adjective','having mixed or conflicting feelings about something','She felt ambivalent about the promotion, pleased by the recognition but uneasy about the longer hours.',['conflicted','torn','uncertain'],['decisive'], 'Hard',90,'Tone & Attitude','He was _____ about moving abroad, excited by the opportunity yet reluctant to leave his family behind.',['ambivalent','emphatic','scornful','candid'],'ambivalent','Ambivalent means holding two opposing feelings at the same time.'),
W('candid','candid','/ˈkændɪd/','adjective','honest and direct, even when the truth is uncomfortable','In a candid interview, the director admitted that the first two films had serious flaws.',['frank','forthright','blunt'],['evasive'], 'Medium',87,'Tone & Attitude','Rather than offering polite praise, the mentor gave a _____ assessment of every weakness in the draft.',['candid','evasive','nostalgic','whimsical'],'candid','Candid means openly honest rather than guarded or flattering.'),
W('dismissive','dismissive','/dɪsˈmɪsɪv/','adjective','treating something as unworthy of serious attention','His dismissive reply suggested he had not bothered to read the proposal at all.',['scornful','disdainful','contemptuous'],['attentive'], 'Medium',86,'Tone & Attitude','The senior engineer was _____ of the intern idea, waving it aside without asking a single question.',['dismissive','deferential','apprehensive','sincere'],'dismissive','Dismissive means brushing something off as not worth considering.'),
W('emphatic','emphatic','/ɪmˈfætɪk/','adjective','expressed forcefully and without any doubt','Her denial was emphatic: she had never seen the document before that morning.',['forceful','insistent','unequivocal'],['tentative'], 'Medium',85,'Tone & Attitude','The mayor was _____ in rejecting the accusation, repeating the denial three times without hesitation.',['emphatic','tentative','ambivalent','wistful'],'emphatic','Emphatic means stated with great force and certainty.'),
W('indifferent','indifferent','/ɪnˈdɪfrənt/','adjective','having no interest in or concern about something','The audience seemed indifferent to the speech, checking phones throughout the entire presentation.',['unconcerned','apathetic','detached'],['invested'], 'Medium',86,'Tone & Attitude','Far from being outraged, most residents were simply _____ to the proposal and never attended the meetings.',['indifferent','indignant','enthusiastic','apprehensive'],'indifferent','Indifferent means feeling no interest either for or against something.'),
W('wary','wary','/ˈwɛri/','adjective','cautious because of possible danger or deception','Investors grew wary after three similar companies collapsed within a single year.',['cautious','guarded','distrustful'],['trusting'], 'Medium',85,'Tone & Attitude','Having been misled once before, the negotiators were _____ of any promise that was not written into the contract.',['wary','reckless','appreciative','solemn'],'wary','Wary means watchful and cautious because harm seems possible.'),
W('earnest','earnest','/ˈɜrnɪst/','adjective','sincere and serious in intention','His earnest apology convinced the committee that the mistake had not been deliberate.',['sincere','heartfelt','genuine'],['flippant'], 'Medium',82,'Tone & Attitude','Her _____ plea for funding moved even the members who had planned to vote against the program.',['earnest','flippant','sardonic','aloof'],'earnest','Earnest means deeply sincere rather than casual or joking.'),
W('impartial','impartial','/ɪmˈpɑrʃəl/','adjective','not favoring one side; free from bias','An impartial reviewer with no ties to either laboratory evaluated both sets of data.',['unbiased','neutral','objective'],['partisan'], 'Hard',89,'Tone & Attitude','Because she had no stake in the outcome, she was asked to serve as an _____ judge of the dispute.',['impartial','partisan','contemptuous','nostalgic'],'impartial','Impartial means judging without favoring either side.'),
W('apprehensive','apprehensive','/ˌæprɪˈhɛnsɪv/','adjective','anxious about something that may happen','Students were apprehensive before the exam, though most had prepared thoroughly for weeks.',['anxious','uneasy','nervous'],['confident'], 'Hard',87,'Tone & Attitude','She grew _____ as the deadline approached, worried that the equipment would fail during the demonstration.',['apprehensive','complacent','exuberant','impartial'],'apprehensive','Apprehensive means uneasy about what might happen next.'),
W('resigned','resigned','/rɪˈzaɪnd/','adjective','accepting something unpleasant that cannot be changed','With a resigned shrug, he accepted that the flight would not leave before morning.',['accepting','submissive','yielding'],['defiant'], 'Hard',84,'Tone & Attitude','After three failed appeals, the family became _____ to the decision and stopped fighting it.',['resigned','defiant','indignant','exuberant'],'resigned','Resigned means accepting an unwelcome outcome without further struggle.'),
W('detached','detached','/dɪˈtætʃt/','adjective','emotionally uninvolved; observing without feeling','The report described the disaster in detached language, listing casualties without comment.',['dispassionate','aloof','impersonal'],['engaged'], 'Medium',85,'Tone & Attitude','The narrator remains oddly _____ throughout the tragedy, describing the loss as though watching strangers.',['detached','sympathetic','indignant','exuberant'],'detached','Detached means observing without emotional involvement.'),
W('deferential','deferential','/ˌdɛfəˈrɛnʃəl/','adjective','showing respect and yielding to the judgment of another','The junior researcher was deferential to her supervisor, rarely questioning his methods in public.',['respectful','submissive','courteous'],['defiant'], 'Hard',83,'Tone & Attitude','His tone became noticeably _____ whenever he addressed the senior members of the committee.',['deferential','dismissive','contemptuous','nonchalant'],'deferential','Deferential means showing respectful submission to someone of higher standing.'),
W('condescending','condescending','/ˌkɑndɪˈsɛndɪŋ/','adjective','behaving as though one is superior to others','His condescending explanation implied that the audience could not follow a simple argument.',['patronizing','superior','haughty'],['respectful'], 'Hard',86,'Tone & Attitude','The tutor adopted a _____ tone, explaining basic terms slowly as if the students were children.',['condescending','deferential','earnest','apprehensive'],'condescending','Condescending means treating others as though they are inferior.'),
W('sardonic','sardonic','/sɑrˈdɑnɪk/','adjective','mocking in a bitter or scornful way','Her sardonic remark about the budget drew uneasy laughter from the room.',['mocking','sarcastic','wry'],['sincere'], 'Hard',84,'Tone & Attitude','He offered a _____ congratulation, praising the plan in words that made his contempt unmistakable.',['sardonic','earnest','reverent','appreciative'],'sardonic','Sardonic means mocking with a bitter edge rather than gentle humor.'),
W('reverent','reverent','/ˈrɛvərənt/','adjective','showing deep respect and admiration','The biography takes a reverent tone, treating every decision of its subject as wise.',['respectful','admiring','worshipful'],['irreverent'], 'Hard',82,'Tone & Attitude','The documentary is so _____ toward its subject that it never raises a single criticism.',['reverent','sardonic','dismissive','indifferent'],'reverent','Reverent means regarding something with deep respect bordering on awe.'),
W('nostalgic','nostalgic','/nɑˈstældʒɪk/','adjective','longing fondly for the past','The essay grows nostalgic when it describes summers spent at his grandmother house.',['wistful','sentimental','longing'],['forward-looking'], 'Medium',81,'Tone & Attitude','The author becomes _____ in later chapters, recalling a childhood she now describes as irretrievably lost.',['nostalgic','apprehensive','contemptuous','impartial'],'nostalgic','Nostalgic means fondly longing for an earlier time.'),
W('appreciative','appreciative','/əˈpriʃətɪv/','adjective','feeling or showing gratitude or admiration','She was appreciative of the feedback, thanking each reviewer for the time they had spent.',['grateful','admiring','thankful'],['dismissive'], 'Medium',80,'Tone & Attitude','Though the review notes several flaws, it remains broadly _____ of what the author achieved.',['appreciative','dismissive','sardonic','indifferent'],'appreciative','Appreciative means showing gratitude or admiration for something.'),
W('cynical','cynical','/ˈsɪnɪkəl/','adjective','believing that people act only from selfish motives','A cynical reading of the donation treats it as nothing more than advertising.',['distrustful','jaded','sardonic'],['idealistic'], 'Hard',88,'Tone & Attitude','His _____ view of the reform assumes that every politician supporting it expects something in return.',['cynical','idealistic','reverent','apprehensive'],'cynical','Cynical means assuming that selfish motives lie behind apparent generosity.'),
W('complacent','complacent','/kəmˈpleɪsənt/','adjective','satisfied with oneself and unaware of possible danger','After two profitable years the company grew complacent and stopped investing in research.',['smug','self-satisfied','unconcerned'],['vigilant'], 'Hard',89,'Tone & Attitude','Early success made the team _____, and they ignored warnings that their lead was shrinking.',['complacent','apprehensive','defiant','earnest'],'complacent','Complacent means so pleased with oneself that risks go unnoticed.'),
W('defiant','defiant','/dɪˈfaɪənt/','adjective','boldly refusing to obey or yield','Defiant to the end, she refused to withdraw the statement despite mounting pressure.',['rebellious','unyielding','resistant'],['submissive'], 'Medium',84,'Tone & Attitude','Rather than apologizing, he remained _____ and repeated the claim in front of the entire committee.',['defiant','deferential','resigned','apprehensive'],'defiant','Defiant means openly refusing to submit or back down.'),
W('indignant','indignant','/ɪnˈdɪɡnənt/','adjective','angry at something unfair or unjust','Residents were indignant that the decision had been made without a single public hearing.',['outraged','affronted','resentful'],['pleased'], 'Hard',86,'Tone & Attitude','The letter is _____ in tone, protesting a ruling the writer considers plainly unjust.',['indignant','indifferent','nostalgic','complacent'],'indignant','Indignant means angered specifically by unfairness.'),
W('ironic','ironic','/aɪˈrɑnɪk/','adjective','meaning the opposite of what is literally said','Calling the flooded basement a swimming pool was his ironic way of coping.',['sarcastic','wry','sardonic'],['literal'], 'Hard',85,'Tone & Attitude','The praise is _____, since every compliment in the passage points to a fault the writer clearly sees.',['ironic','literal','earnest','reverent'],'ironic','Ironic means saying one thing while clearly meaning its opposite.'),
W('melancholy','melancholy','/ˈmɛlənkɑli/','adjective','filled with a thoughtful, lingering sadness','A melancholy mood settles over the final chapters as the characters drift apart.',['sorrowful','wistful','somber'],['cheerful'], 'Hard',82,'Tone & Attitude','The poem grows _____ toward the end, dwelling on friendships that time has quietly dissolved.',['melancholy','exuberant','indignant','complacent'],'melancholy','Melancholy means a reflective, lingering sadness rather than sharp grief.'),
W('optimistic','optimistic','/ˌɑptɪˈmɪstɪk/','adjective','expecting good things to happen','Despite the delays, the engineers stayed optimistic that the launch would happen that year.',['hopeful','positive','confident'],['pessimistic'], 'Easy',76,'Tone & Attitude','The forecast is cautiously _____, predicting slow but steady improvement over the next two quarters.',['optimistic','pessimistic','indignant','sardonic'],'optimistic','Optimistic means expecting a favorable outcome.'),
W('pessimistic','pessimistic','/ˌpɛsɪˈmɪstɪk/','adjective','expecting the worst outcome','Early reviewers were pessimistic about the project, predicting it would never reach production.',['gloomy','doubtful','despairing'],['optimistic'], 'Easy',76,'Tone & Attitude','His _____ estimate assumed that every remaining stage of the work would run over budget.',['pessimistic','optimistic','reverent','nonchalant'],'pessimistic','Pessimistic means expecting an unfavorable outcome.'),
W('sincere','sincere','/sɪnˈsɪr/','adjective','genuine and free from pretense','Her sincere interest in the subject was obvious from the questions she asked afterward.',['genuine','heartfelt','earnest'],['insincere'], 'Easy',75,'Tone & Attitude','The thanks felt _____ rather than formal, since he named each person and what they had done.',['sincere','sardonic','condescending','indifferent'],'sincere','Sincere means genuinely meant rather than performed.'),
W('solemn','solemn','/ˈsɑləm/','adjective','serious, formal, and without humor','The ceremony was solemn, with no music and only a brief address from the chairman.',['grave','serious','somber'],['lighthearted'], 'Medium',80,'Tone & Attitude','The occasion called for a _____ tone, so the speaker set aside the jokes she had prepared.',['solemn','whimsical','sardonic','exuberant'],'solemn','Solemn means seriously formal and free of levity.'),
W('sympathetic','sympathetic','/ˌsɪmpəˈθɛtɪk/','adjective','feeling or showing understanding of the suffering of others','The article is sympathetic to the workers, describing their long hours without condescension.',['compassionate','understanding','supportive'],['unfeeling'], 'Medium',81,'Tone & Attitude','Although the author disagrees with the protesters, her account of their hardship is genuinely _____.',['sympathetic','contemptuous','indifferent','sardonic'],'sympathetic','Sympathetic means showing understanding and concern for what others endure.'),
W('whimsical','whimsical','/ˈwɪmzɪkəl/','adjective','playfully odd or fanciful','The garden had a whimsical quality, with painted doors set into the trunks of trees.',['playful','fanciful','quirky'],['solemn'], 'Hard',79,'Tone & Attitude','The illustrations are deliberately _____, filling a serious history with talking animals and impossible machines.',['whimsical','solemn','indignant','impartial'],'whimsical','Whimsical means playfully fanciful rather than serious.'),
W('aloof','aloof','/əˈluf/','adjective','distant and uninvolved with other people','He remained aloof at the reception, speaking to no one for the entire evening.',['distant','remote','standoffish'],['sociable'], 'Hard',83,'Tone & Attitude','New colleagues mistook her quiet manner for being _____, though she was simply unsure of herself.',['aloof','sympathetic','exuberant','earnest'],'aloof','Aloof means keeping emotionally and socially distant from others.'),
W('contemptuous','contemptuous','/kənˈtɛmptʃuəs/','adjective','showing scorn for something considered worthless','A contemptuous review called the exhibit an insult to everyone who paid to see it.',['scornful','disdainful','derisive'],['admiring'], 'Hard',85,'Tone & Attitude','The critic is openly _____ of the film, describing it as an insult to the audience.',['contemptuous','appreciative','deferential','ambivalent'],'contemptuous','Contemptuous means regarding something with active scorn.'),
W('incredulous','incredulous','/ɪnˈkrɛdʒələs/','adjective','unwilling or unable to believe something','She gave him an incredulous look when he claimed to have finished the whole book overnight.',['disbelieving','skeptical','doubtful'],['credulous'], 'Hard',84,'Tone & Attitude','The audience was _____ when the speaker announced a figure ten times larger than any previous estimate.',['incredulous','complacent','deferential','nostalgic'],'incredulous','Incredulous means unable to believe what one has just heard.'),
W('nonchalant','nonchalant','/ˌnɑnʃəˈlɑnt/','adjective','calmly unconcerned in a way that seems casual','He was nonchalant about the missed deadline, as though it hardly mattered at all.',['unconcerned','casual','indifferent'],['anxious'], 'Hard',82,'Tone & Attitude','Her _____ response to the warning surprised everyone, since the rest of the crew were visibly alarmed.',['nonchalant','apprehensive','indignant','earnest'],'nonchalant','Nonchalant means appearing calmly untroubled by something others find serious.'),
W('remorseful','remorseful','/rɪˈmɔrsfəl/','adjective','deeply regretful for having done wrong','Remorseful about the delay, the supplier waived the fee without being asked.',['regretful','contrite','apologetic'],['unrepentant'], 'Medium',79,'Tone & Attitude','He seemed genuinely _____, offering to repair the damage himself before anyone requested it.',['remorseful','defiant','nonchalant','complacent'],'remorseful','Remorseful means feeling deep regret for a wrong one has done.'),
W('scornful','scornful','/ˈskɔrnfəl/','adjective','expressing open contempt','The editorial was scornful of the plan, calling it the least serious proposal yet offered.',['contemptuous','derisive','disdainful'],['respectful'], 'Medium',82,'Tone & Attitude','Her _____ laugh made it plain that she considered the suggestion beneath discussion.',['scornful','reverent','sympathetic','apprehensive'],'scornful','Scornful means openly showing contempt.'),
W('somber','somber','/ˈsɑmbər/','adjective','dark, grave, and serious in mood','The somber tone of the final report reflected how little had survived the fire.',['grave','gloomy','solemn'],['cheerful'], 'Medium',80,'Tone & Attitude','The mood in the room turned _____ once the extent of the losses became clear.',['somber','exuberant','whimsical','nonchalant'],'somber','Somber means darkly serious in mood.'),
W('vindictive','vindictive','/vɪnˈdɪktɪv/','adjective','seeking revenge rather than justice','The dismissal seemed vindictive, arriving days after she testified against the company.',['vengeful','spiteful','retaliatory'],['forgiving'], 'Hard',83,'Tone & Attitude','Critics called the punishment _____, arguing it was designed to humiliate rather than to correct.',['vindictive','forgiving','deferential','impartial'],'vindictive','Vindictive means motivated by a desire for revenge.'),
W('exuberant','exuberant','/ɪɡˈzubərənt/','adjective','filled with lively, overflowing energy','The crowd was exuberant, singing in the streets long after the final whistle.',['enthusiastic','jubilant','high-spirited'],['subdued'], 'Hard',81,'Tone & Attitude','The prose turns _____ in these chapters, piling image upon image with obvious delight.',['exuberant','somber','detached','wary'],'exuberant','Exuberant means overflowing with lively energy and enthusiasm.'),
];
