// GENERATED by scripts/build-wordnet.mjs. Do not edit.
/* eslint-disable */
export const loadShard = (c: string): Record<string, string[]> | null => {
  switch (c) {
    case 'a': return require('../data/wordnet/a.json');
    case 'b': return require('../data/wordnet/b.json');
    case 'c': return require('../data/wordnet/c.json');
    case 'd': return require('../data/wordnet/d.json');
    case 'e': return require('../data/wordnet/e.json');
    case 'f': return require('../data/wordnet/f.json');
    case 'g': return require('../data/wordnet/g.json');
    case 'h': return require('../data/wordnet/h.json');
    case 'i': return require('../data/wordnet/i.json');
    case 'j': return require('../data/wordnet/j.json');
    case 'k': return require('../data/wordnet/k.json');
    case 'l': return require('../data/wordnet/l.json');
    case 'm': return require('../data/wordnet/m.json');
    case 'n': return require('../data/wordnet/n.json');
    case 'o': return require('../data/wordnet/o.json');
    case 'p': return require('../data/wordnet/p.json');
    case 'q': return require('../data/wordnet/q.json');
    case 'r': return require('../data/wordnet/r.json');
    case 's': return require('../data/wordnet/s.json');
    case 't': return require('../data/wordnet/t.json');
    case 'u': return require('../data/wordnet/u.json');
    case 'v': return require('../data/wordnet/v.json');
    case 'w': return require('../data/wordnet/w.json');
    case 'x': return require('../data/wordnet/x.json');
    case 'y': return require('../data/wordnet/y.json');
    case 'z': return require('../data/wordnet/z.json');
    default: return null;
  }
};
